spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: homepage
          uri: lb://gateway-service
          predicates:
            - Path=/ir/aspireapps/linker/home

        - id: links-service
          uri: lb://links-service
          predicates:
            - Path=/ir/aspireapps/visit/**, /ir/aspireapps/linker/links/api/v1/visit/**

        - id: gateway-server-api
          uri: lb://gateway-service
          predicates:
            - Path=/ir/aspireapps/linker/gateway/api/v1/**

        - id: gateway-server-web
          uri: lb://gateway-service
          predicates:
            - Path=/ir/aspireapps/linker/gateway/web/v1/**

        - id: user-service-api
          uri: lb://user-service
          predicates:
            - Path=/ir/aspireapps/linker/auth/api/v1/**,/ir/aspireapps/linker/user/api/v1/**

        - id: user-service-web
          uri: lb://user-service
          predicates:
            - Path=/ir/aspireapps/linker/auth/web/v1/**,/ir/aspireapps/linker/user/web/v1/**
          filters:
            - PreserveHostHeader

        - id: analysis-service
          uri: lb://analysis-service
          predicates:
            - Path=/ir/aspireapps/linker/analysis/api/v1/**
          filters:
            - PreserveHostHeader
security:
  jwt:
    secretKey: ${ACCESS_TOKEN_SECURITY_KEY}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    wait-time-in-ms-when-sync-empty: 0