spring:
  application:
    name: user-service

  server:
    wait-time-in-ms-when-sync-emtpy: 0

  datasource:
    url: jdbc:postgresql://postgres:5432/linker_user_db
    username: demoapps
    password: JingleBells
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: none
      open-in-view: false
      show-sql: true
      properties:
        hibernate:
          format-sql: true

    sql:
      init:
        mode: always
        platform: postgres

    flyway:
      enabled: true
      location: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    ir.aspireapps: DEBUG
    feign: DEBUG

security:
  jwt:
    access-token-secret-key: "A-VERY-STRONG-SECRET-KEY-FOR-ACCESS-TOKEN"
    access-token-expiration-ms: 900_000 #1000 * 60 * 15
    refresh-token-expiration-ms: 604_800_000 #1000 * 60 * 60 * 24 * 7